# Site settings
title: Reboot SNU-서울대의 새로운 비상
email: wilee@snu.ac.kr
description: > # Writer Theme is a responsive template
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reboot-snu.github.io" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
disqus: "https-reboot-snu-github-io"
nav_list:
  Home : ['홈으로', '/', 'fa-home']
  Devplan: ['발전계획서', '/devplan', 'fa-power-off']
  Posts : ['이우일의 생각', '/posts', 'fa-newspaper-o']
  About : ['이우일은..', '/about', 'fa-user']
  Talk : ['이우일과의 대화', '/talk', 'fa-comments-o']
single_footer: '<p>Reboot SNU: 서울대의 새로운 비상. &copy; 2018</p>'
footer_links:
  Home : ['홈으로', '/']
  Devplan: ['발전계획서', 'devplan']
  Posts : ['이우일의 생각', '/posts']
  About : ['이우일은', '/about']
  Talk : ['이우일과의 대화', '/talk']

# Build settings
# markdown: kramdown
